# Generated by Django 5.2.4 on 2025-07-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_book_author_alter_book_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='books',
        ),
        migrations.AddField(
            model_name='library',
            name='book',
            field=models.ManyToManyField(related_name='libraries', to='relationship_app.book'),
        ),
    ]
